//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class dashboard_earning
    {
        public string ReceiptNo { get; set; }
        public string ReceiptDate { get; set; }
        public string Property_Name { get; set; }
        public string unit_Name { get; set; }
        public string Tenant_Name { get; set; }
        public float TotalAmount { get; set; }
        public string Month { get; set; }
        public Nullable<long> year { get; set; }
    }
}
