//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class dashboard_expenses
    {
        public int id { get; set; }
        public string PaymentNo { get; set; }
        public string PaymentDate { get; set; }
        public string Utility_name { get; set; }
        public string Supplier_name { get; set; }
        public string PaymentType { get; set; }
        public string PaymentMode { get; set; }
        public float TotalAmount { get; set; }
    }
}
