//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebwater_report
    {
        public int id { get; set; }
        public Nullable<int> Refno { get; set; }
        public string Meterno { get; set; }
        public string property_id { get; set; }
        public string Property_Name { get; set; }
        public string Unit_id { get; set; }
        public string Unit_Property_Name { get; set; }
        public Nullable<float> Total_units { get; set; }
        public string Meterreadingno { get; set; }
        public Nullable<System.DateTime> Reading_date { get; set; }
        public Nullable<System.DateTime> billdate { get; set; }
        public Nullable<int> billno { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public string utility_id { get; set; }
        public string Utility_Name { get; set; }
        public string Region_Name { get; set; }
        public string country { get; set; }
        public string Caretaker_Name { get; set; }
        public Nullable<int> Caretaker_ID { get; set; }
        public Nullable<double> Billamount { get; set; }
        public Nullable<double> Paidamount { get; set; }
        public Nullable<double> OutstandingAmt { get; set; }
        public Nullable<int> Aging_Days { get; set; }
        public string user { get; set; }
    }
}
