//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_newagreement
    {
        public int id { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public string TemplateName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string SubjectParameter { get; set; }
        public string BodyParameter { get; set; }
        public int Agreement_No { get; set; }
        public string Ag_Tenant_Name { get; set; }
        public string Propertyid { get; set; }
        public string Propertyname { get; set; }
        public Nullable<System.DateTime> Agreement_Start_Date { get; set; }
        public Nullable<System.DateTime> Agreement_End_Date { get; set; }
        public Nullable<float> Total_Rental_amount { get; set; }
        public string Tenant_Type { get; set; }
        public string Emailid { get; set; }
    }
}
