//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_output
    {
        public int id { get; set; }
        public string TemplateId { get; set; }
        public string Templatename { get; set; }
        public string toid { get; set; }
        public string cc { get; set; }
        public string bcc { get; set; }
        public string Subject { get; set; }
        public string body { get; set; }
        public string toparameter { get; set; }
        public string ccparameter { get; set; }
        public string bccparameter { get; set; }
        public string Subjectparameter { get; set; }
        public string bodyparameter { get; set; }
        public string signature { get; set; }
        public string Mailstatus { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string Error { get; set; }
    }
}
