//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class summaryebwater_treand
    {
        public string Monthname { get; set; }
        public Nullable<int> mno { get; set; }
        public Nullable<int> Yearno { get; set; }
        public Nullable<double> units { get; set; }
        public Nullable<double> Paidamount { get; set; }
        public string utility_name { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
        public string user { get; set; }
    }
}
