//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class summarycollection_report
    {
        public int id { get; set; }
        public int property_id { get; set; }
        public string Property_ID_Tawtheeq { get; set; }
        public string Properties_Name { get; set; }
        public string Unit_ID_Tawtheeq { get; set; }
        public string Unit_Property_Name { get; set; }
        public int Caretaker_id { get; set; }
        public string Caretaker_Name { get; set; }
        public int Ag_Tenant_id { get; set; }
        public string Ag_Tenant_Name { get; set; }
        public string country { get; set; }
        public string region_name { get; set; }
        public string Reccategory { get; set; }
        public string RecpType { get; set; }
        public string pdcstatus { get; set; }
        public string DDChequeNo { get; set; }
        public Nullable<System.DateTime> DDChequeDate { get; set; }
        public Nullable<float> Total_Rental_amount { get; set; }
        public Nullable<float> totalamount { get; set; }
        public string user { get; set; }
    }
}
