//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class summaryebwater_colour
    {
        public long Refno { get; set; }
        public string Meterno { get; set; }
        public string property_id { get; set; }
        public string Property_Name { get; set; }
        public string Unit_id { get; set; }
        public string Unit_Property_Name { get; set; }
        public float Total_units { get; set; }
        public string Meterreadingno { get; set; }
        public string Reading_date { get; set; }
        public string billdate { get; set; }
        public long billno { get; set; }
        public string duedate { get; set; }
        public string utility_id { get; set; }
        public string Utility_Name { get; set; }
        public string Region_Name { get; set; }
        public string country { get; set; }
        public string Caretaker_Name { get; set; }
        public long Caretaker_ID { get; set; }
        public double Billamount { get; set; }
        public double Paidamount { get; set; }
        public long Aging_Days { get; set; }
        public string user { get; set; }
        public string Monthname { get; set; }
        public Nullable<int> mno { get; set; }
        public Nullable<int> yearno { get; set; }
        public string colour { get; set; }
    }
}
