//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tenant_individual
    {
        public int Id { get; set; }
        public int Tenant_Id { get; set; }
        public string Title { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Company_Educational { get; set; }
        public string Profession { get; set; }
        public string Marital_Status { get; set; }
        public string address { get; set; }
        public string address1 { get; set; }
        public string Emirate { get; set; }
        public string City { get; set; }
        public string PostboxNo { get; set; }
        public string Email { get; set; }
        public string Mobile_Countrycode { get; set; }
        public string Mobile_Areacode { get; set; }
        public string Mobile_No { get; set; }
        public string Landline_Countrycode { get; set; }
        public string Landline_Areacode { get; set; }
        public string Landline_No { get; set; }
        public string Fax_Countrycode { get; set; }
        public string Fax_Areacode { get; set; }
        public string Fax_No { get; set; }
        public string Nationality { get; set; }
        public string Emiratesid { get; set; }
        public Nullable<System.DateTime> Emirate_issuedate { get; set; }
        public Nullable<System.DateTime> Emirate_expirydate { get; set; }
        public string Passportno { get; set; }
        public string Placeofissuance { get; set; }
        public Nullable<System.DateTime> Passport_Issuedate { get; set; }
        public Nullable<System.DateTime> Passport_Expirydate { get; set; }
        public string VisaType { get; set; }
        public string Visano { get; set; }
        public Nullable<System.DateTime> Visa_IssueDate { get; set; }
        public Nullable<System.DateTime> Visa_ExpiryDate { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Familyno { get; set; }
        public string Familybookcity { get; set; }
        public string ADWEA_Regid { get; set; }
        public string Type { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
    }
}
