//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_propertiesmaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_propertiesmaster()
        {
            this.tbl_agreement = new HashSet<tbl_agreement>();
            this.tbl_propertiesdt = new HashSet<tbl_propertiesdt>();
            this.tbl_propertiesdt1 = new HashSet<tbl_propertiesdt1>();
        }
    
        public int id { get; set; }
        public string Property_Flag { get; set; }
        public string Property_ID_Tawtheeq { get; set; }
        public int Property_Id { get; set; }
        public string Property_Name { get; set; }
        public string Compound { get; set; }
        public string Zone { get; set; }
        public string sector { get; set; }
        public string plotno { get; set; }
        public Nullable<int> ownedbyregistrant { get; set; }
        public string Property_Usage { get; set; }
        public string Property_Type { get; set; }
        public Nullable<int> Commercial_villa { get; set; }
        public string Street_Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Externalrefno { get; set; }
        public Nullable<int> Noofoffloors { get; set; }
        public Nullable<int> Noofunits { get; set; }
        public Nullable<float> Builtarea { get; set; }
        public Nullable<float> Plotarea { get; set; }
        public Nullable<float> Leasablearea { get; set; }
        public Nullable<float> commonarea { get; set; }
        public Nullable<System.DateTime> completion_Date { get; set; }
        public Nullable<float> AEDvalue { get; set; }
        public Nullable<System.DateTime> Purchased_date { get; set; }
        public Nullable<System.DateTime> Valued_Date { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Vacant_Start_Date { get; set; }
        public string Caretaker_Name { get; set; }
        public Nullable<int> Caretaker_ID { get; set; }
        public Nullable<float> Rental_Rate_Month { get; set; }
        public string Comments { get; set; }
        public string Ref_unit_Property_ID_Tawtheeq { get; set; }
        public Nullable<int> Ref_Unit_Property_ID { get; set; }
        public string Ref_Unit_Property_Name { get; set; }
        public string Unit_ID_Tawtheeq { get; set; }
        public string Unit_Property_Name { get; set; }
        public string Externalrefno_unit { get; set; }
        public Nullable<float> AEDvalue_unit { get; set; }
        public Nullable<System.DateTime> Purchased_date_unit { get; set; }
        public Nullable<System.DateTime> Valued_Date_unit { get; set; }
        public string Status_unit { get; set; }
        public Nullable<System.DateTime> Vacant_Start_Date_Unit { get; set; }
        public Nullable<float> Rental_Rate_Month_unit { get; set; }
        public string Floorno { get; set; }
        public string Floorlevel { get; set; }
        public string Property_Usage_unit { get; set; }
        public string Property_Type_unit { get; set; }
        public Nullable<float> Total_Area { get; set; }
        public Nullable<float> Unit_Common_Area { get; set; }
        public Nullable<float> Common_Area { get; set; }
        public Nullable<int> Parkingno { get; set; }
        public string Unitcomments { get; set; }
        public Nullable<int> Company_occupied_Flag { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_agreement> tbl_agreement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_propertiesdt> tbl_propertiesdt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_propertiesdt1> tbl_propertiesdt1 { get; set; }
    }
}
