//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userrights
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Userid { get; set; }
        public string Pwd { get; set; }
        public string Cnfpwd { get; set; }
        public string Category { get; set; }
        public string Email { get; set; }
        public string Phoneno { get; set; }
        public Nullable<int> AddConfig { get; set; }
        public Nullable<int> EditConfig { get; set; }
        public Nullable<int> DeleteConfig { get; set; }
        public string MenuConfig { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
    }
}
