//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_log
    {
        public int Id { get; set; }
        public string Table_Name { get; set; }
        public string Operations { get; set; }
        public Nullable<System.DateTime> Opeartion_Datetime { get; set; }
        public string Login_username { get; set; }
        public string Keyfield { get; set; }
        public string Keyfieldvalue { get; set; }
        public string Machine_Name { get; set; }
        public string Procedure_Name { get; set; }
    }
}
