//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_eb_water_billentrydt
    {
        public int id { get; set; }
        public Nullable<int> Refno { get; set; }
        public string Meterno { get; set; }
        public string property_id { get; set; }
        public string Unit_id { get; set; }
        public Nullable<float> Total_units { get; set; }
        public string Meterreadingno { get; set; }
        public Nullable<System.DateTime> Reading_date { get; set; }
        public Nullable<System.DateTime> billdate { get; set; }
        public Nullable<int> billno { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<int> daysofuse { get; set; }
        public Nullable<float> rate { get; set; }
        public Nullable<float> amount { get; set; }
        public string Delmark { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
    
        public virtual tbl_eb_water_billentryhd tbl_eb_water_billentryhd { get; set; }
        public virtual tbl_metermaster tbl_metermaster { get; set; }
    }
}
