//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_agreement_status
    {
        public int id { get; set; }
        public int Agreement_No { get; set; }
        public Nullable<int> Ag_Tenant_id { get; set; }
        public string Ag_Tenant_Name { get; set; }
        public Nullable<int> Properties_ID { get; set; }
        public string Properties_Name { get; set; }
        public Nullable<int> Caretaker_id { get; set; }
        public string Caretaker_Name { get; set; }
        public string Unit_id { get; set; }
        public string Unit_name { get; set; }
        public string Renewal_Close_Flag { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
    }
}
