//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_metermaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_metermaster()
        {
            this.tbl_eb_water_billentrydt = new HashSet<tbl_eb_water_billentrydt>();
        }
    
        public int id { get; set; }
        public string Utility_id { get; set; }
        public string Utility_Name { get; set; }
        public string Meter_no { get; set; }
        public string Accno { get; set; }
        public string Property_id { get; set; }
        public string unit_id { get; set; }
        public Nullable<int> Dueday { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_eb_water_billentrydt> tbl_eb_water_billentrydt { get; set; }
        public virtual tbl_utilitiesmaster tbl_utilitiesmaster { get; set; }
    }
}
