//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_agreement_closure_utility
    {
        public int id { get; set; }
        public Nullable<int> Agreement_No { get; set; }
        public string Utility_id { get; set; }
        public string Utility_Name { get; set; }
        public string Payable { get; set; }
        public string Amount_Type { get; set; }
        public Nullable<float> Amount { get; set; }
        public string Delmark { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
    
        public virtual tbl_agreement_closure tbl_agreement_closure { get; set; }
    }
}
