//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplierdt1
    {
        public int id { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public string Cper { get; set; }
        public string Cpercode { get; set; }
        public string Desig { get; set; }
        public string Dept { get; set; }
        public string Phone { get; set; }
        public string Ext { get; set; }
        public string MobNo { get; set; }
        public string Salutations { get; set; }
        public Nullable<int> Accyear { get; set; }
        public string Delmark { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
    
        public virtual tbl_suppliermaster tbl_suppliermaster { get; set; }
    }
}
