//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_caretaker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_caretaker()
        {
            this.tbl_agreement = new HashSet<tbl_agreement>();
            this.tbl_propertiesmaster = new HashSet<tbl_propertiesmaster>();
        }
    
        public int Id { get; set; }
        public int Caretaker_id { get; set; }
        public string Caretaker_Name { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string Phoneno { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Doj { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_agreement> tbl_agreement { get; set; }
        public virtual tbl_region tbl_region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_propertiesmaster> tbl_propertiesmaster { get; set; }
    }
}
