//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aging_range
    {
        public int id { get; set; }
        public Nullable<int> Range_From { get; set; }
        public Nullable<int> Range_To { get; set; }
        public string Range_Display { get; set; }
        public string category { get; set; }
    }
}
