//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_errorlog
    {
        public int Id { get; set; }
        public string Procedure_Name { get; set; }
        public string Error_Text { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string User { get; set; }
        public string Machine_Name { get; set; }
    }
}
