//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_slabmaster
    {
        public int id { get; set; }
        public Nullable<int> slabid { get; set; }
        public string Utility_id { get; set; }
        public string Utility_Name { get; set; }
        public Nullable<int> Unit_From { get; set; }
        public Nullable<int> Unitto { get; set; }
        public Nullable<float> rate { get; set; }
        public string Colour { get; set; }
        public string Residence_type { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
    }
}
