//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_receipthd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_receipthd()
        {
            this.tbl_receiptdt = new HashSet<tbl_receiptdt>();
        }
    
        public int id { get; set; }
        public string Reccategory { get; set; }
        public string RecpType { get; set; }
        public int ReceiptNo { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<int> agreement_no { get; set; }
        public string Property_id { get; set; }
        public string Property_Name { get; set; }
        public string Unit_ID { get; set; }
        public string unit_Name { get; set; }
        public Nullable<int> Tenant_id { get; set; }
        public string Tenant_Name { get; set; }
        public Nullable<float> TotalAmount { get; set; }
        public string AmtInWords { get; set; }
        public string DDChequeNo { get; set; }
        public string PDCstatus { get; set; }
        public string BankAcCode { get; set; }
        public string BankAcName { get; set; }
        public string AdvAcCode { get; set; }
        public Nullable<System.DateTime> DDChequeDate { get; set; }
        public string Narration { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_receiptdt> tbl_receiptdt { get; set; }
    }
}
