//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_paymentdt
    {
        public int id { get; set; }
        public Nullable<int> PaymentNo { get; set; }
        public string Invtype { get; set; }
        public string Description { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<float> InvoiceAmount { get; set; }
        public Nullable<float> PaidAmount { get; set; }
        public Nullable<float> Debitamt { get; set; }
        public string Remarks { get; set; }
        public string Delmark { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
    
        public virtual tbl_paymenthd tbl_paymenthd { get; set; }
    }
}
