//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplierdt
    {
        public int id { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public string Branch { get; set; }
        public string BranchAdd { get; set; }
        public string Branchadd1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string PhoneNo { get; set; }
        public string EMailID { get; set; }
        public string FaxNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Accyear { get; set; }
        public string Delmark { get; set; }
    
        public virtual tbl_suppliermaster tbl_suppliermaster { get; set; }
    }
}
