//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoicehd
    {
        public int id { get; set; }
        public string invno { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> Tenant_id { get; set; }
        public string Tenant_Name { get; set; }
        public string invtype { get; set; }
        public Nullable<int> Agreement_No { get; set; }
        public string Property_ID { get; set; }
        public string Property_Name { get; set; }
        public string Unit_ID { get; set; }
        public string unit_Name { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<float> totalamt { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public string bank_details { get; set; }
        public string remarks { get; set; }
        public Nullable<int> incno { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoicedt> tbl_invoicedt { get; set; }
    }
}
