//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emailtemplate
    {
        public int Id { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public string TemplateName { get; set; }
        public string toid { get; set; }
        public string cc { get; set; }
        public string bcc { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Bodytext { get; set; }
        public string toparameter { get; set; }
        public string ccparameter { get; set; }
        public string bccparameter { get; set; }
        public string SubjectParameter { get; set; }
        public string BodyParameter { get; set; }
        public Nullable<bool> InActive { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string SubjectText { get; set; }
        public string BodyTextParam { get; set; }
        public string SubjectParameterText { get; set; }
        public string BodyParameterText { get; set; }
        public string signature { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
    }
}
