//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilitybill_notgenerated
    {
        public string Property_Name { get; set; }
        public string Unit_Property_Name { get; set; }
        public string Caretaker_Name { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
        public int id { get; set; }
        public string Utility_id { get; set; }
        public string Utility_Name { get; set; }
        public string Meter_no { get; set; }
        public string Accno { get; set; }
        public string Property_id { get; set; }
        public string unit_id { get; set; }
        public Nullable<int> Dueday { get; set; }
        public Nullable<int> Accyear { get; set; }
        public Nullable<System.DateTime> Createddatetime { get; set; }
        public string Createduser { get; set; }
        public string Delmark { get; set; }
        public string user { get; set; }
    }
}
