//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacancy_caretaker_report
    {
        public Nullable<int> Caretaker_id { get; set; }
        public string Caretaker_Name { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
        public long Noof_properties { get; set; }
        public Nullable<int> Aging_days { get; set; }
        public string Aging_Range { get; set; }
        public string Amont_Range { get; set; }
        public Nullable<double> Loss_Amt { get; set; }
        public string user { get; set; }
    }
}
