//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_invoice_receipt_pending
    {
        public string invno { get; set; }
        public Nullable<int> Agreement_No { get; set; }
        public string Property_ID { get; set; }
        public string Property_Name { get; set; }
        public string Unit_ID { get; set; }
        public string unit_Name { get; set; }
        public Nullable<int> Tenant_id { get; set; }
        public string Tenant_Name { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> incno { get; set; }
        public string invtype { get; set; }
        public Nullable<float> totalamt { get; set; }
        public string remarks { get; set; }
        public string Description { get; set; }
        public Nullable<double> InvoiceAmount { get; set; }
        public string Region_name { get; set; }
        public string Country { get; set; }
    }
}
