//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_security_pending
    {
        public Nullable<int> Agreement_No { get; set; }
        public Nullable<int> Tenant_id { get; set; }
        public string Tenant_Name { get; set; }
        public string Property_id { get; set; }
        public string Property_Name { get; set; }
        public string Unit_ID { get; set; }
        public string unit_Name { get; set; }
        public Nullable<double> Security_Amount { get; set; }
        public string DDChequeNo { get; set; }
        public string Security_Flag { get; set; }
        public string Security_chequedate { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
    }
}
