//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_agree_recp_chequenowise_pending
    {
        public Nullable<int> Agreement_No { get; set; }
        public string Cheque_No { get; set; }
        public string Cheque_Date { get; set; }
        public Nullable<double> amount { get; set; }
        public string Payment_Mode { get; set; }
    }
}
