//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_agreement_close_pending
    {
        public Nullable<int> agreement_no { get; set; }
        public Nullable<double> totalamount { get; set; }
        public double paidamount { get; set; }
        public double advancepending { get; set; }
    }
}
