//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_propertymastergridfill
    {
        public int Property_Id { get; set; }
        public string Property_Type { get; set; }
        public string Property_Flag { get; set; }
        public string Property_ID_Tawtheeq { get; set; }
        public string Property_Name { get; set; }
        public string Unit_ID_Tawtheeq { get; set; }
        public string Unit_Property_Name { get; set; }
        public string Status { get; set; }
        public string Region_name { get; set; }
        public string Country { get; set; }
    }
}
