//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaMaPortal.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_security
    {
        public Nullable<int> Agreement_No { get; set; }
        public Nullable<int> Ag_Tenant_id { get; set; }
        public string Ag_Tenant_Name { get; set; }
        public string Property_ID_Tawtheeq { get; set; }
        public string Properties_Name { get; set; }
        public string Unit_ID_Tawtheeq { get; set; }
        public string Unit_Property_Name { get; set; }
        public Nullable<double> Advance_Security_Amount { get; set; }
        public string Security_chequeno { get; set; }
        public string Security_Flag { get; set; }
        public string Security_chequedate { get; set; }
        public string Region_Name { get; set; }
        public string Country { get; set; }
    }
}
